// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetArchiveContents(arg1) {
  return window['go']['app']['App']['GetArchiveContents'](arg1);
}

export function GetDirContents(arg1) {
  return window['go']['app']['App']['GetDirContents'](arg1);
}

export function GetImageData(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetImageData'](arg1, arg2, arg3);
}

export function GetImageList(arg1, arg2) {
  return window['go']['app']['App']['GetImageList'](arg1, arg2);
}

export function GetImageRange(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetImageRange'](arg1, arg2, arg3, arg4);
}

export function GetLastSelection() {
  return window['go']['app']['App']['GetLastSelection']();
}

export function GetRootDirectory() {
  return window['go']['app']['App']['GetRootDirectory']();
}

export function GetSeriesList() {
  return window['go']['app']['App']['GetSeriesList']();
}

export function GetVolumeList(arg1) {
  return window['go']['app']['App']['GetVolumeList'](arg1);
}

export function GetZipContents(arg1) {
  return window['go']['app']['App']['GetZipContents'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['app']['App']['OpenDirectoryDialog']();
}

export function SaveLastSelection(arg1, arg2) {
  return window['go']['app']['App']['SaveLastSelection'](arg1, arg2);
}

export function SetRootDirectory(arg1) {
  return window['go']['app']['App']['SetRootDirectory'](arg1);
}
