// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetArchiveContents(arg1:string):Promise<Array<app.VolumeInfo>>;

export function GetDirContents(arg1:string):Promise<Array<app.VolumeInfo>>;

export function GetImageData(arg1:string,arg2:boolean,arg3:number):Promise<app.ImageInfo>;

export function GetImageList(arg1:string,arg2:boolean):Promise<Array<string>>;

export function GetImageRange(arg1:string,arg2:boolean,arg3:number,arg4:number):Promise<Array<app.ImageInfo>>;

export function GetLastSelection():Promise<Record<string, string>>;

export function GetRootDirectory():Promise<string>;

export function GetSeriesList():Promise<Array<string>>;

export function GetVolumeList(arg1:string):Promise<Array<app.VolumeInfo>>;

export function GetZipContents(arg1:string):Promise<Array<app.VolumeInfo>>;

export function OpenDirectoryDialog():Promise<string>;

export function SaveLastSelection(arg1:string,arg2:string):Promise<void>;

export function SetRootDirectory(arg1:string):Promise<void>;
